'use client';

import { getCampaignTotals, demoDecayAlerts, demoChurnScores } from '@/lib/demo-data';
import { printContent } from '@/lib/export-utils';
import { Printer, Mail, Copy, CheckCircle } from 'lucide-react';
import { useState } from 'react';

const totals = getCampaignTotals();

export default function Briefing() {
  const [copied, setCopied] = useState(false);
  const date = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });

  const briefingHtml = `
<div style="max-width:600px;margin:0 auto;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="background:linear-gradient(135deg,#1B3A5C,#122840);padding:24px;border-radius:12px 12px 0 0;">
    <h1 style="color:white;font-size:18px;margin:0;">MEMTrak Daily Briefing</h1>
    <p style="color:rgba(255,255,255,0.5);font-size:12px;margin:4px 0 0;">${date}</p>
  </div>
  <div style="background:white;padding:24px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px;">
    <h2 style="color:#1B3A5C;font-size:14px;border-bottom:2px solid #8CC63F;padding-bottom:4px;">Key Metrics (Apr YTD)</h2>
    <table style="width:100%;border-collapse:collapse;font-size:12px;margin:12px 0;">
      <tr><td style="padding:6px 0;"><strong>Emails Sent:</strong></td><td style="text-align:right;">${totals.totalSent.toLocaleString()}</td></tr>
      <tr><td style="padding:6px 0;"><strong>Open Rate:</strong></td><td style="text-align:right;">${((totals.totalOpened / totals.totalDelivered) * 100).toFixed(1)}%</td></tr>
      <tr><td style="padding:6px 0;"><strong>Click Rate:</strong></td><td style="text-align:right;">${((totals.totalClicked / totals.totalDelivered) * 100).toFixed(1)}%</td></tr>
      <tr><td style="padding:6px 0;"><strong>Revenue Attributed:</strong></td><td style="text-align:right;color:#8CC63F;font-weight:bold;">$${(totals.totalRevenue / 1000).toFixed(0)}K</td></tr>
      <tr><td style="padding:6px 0;"><strong>Bounce Rate:</strong></td><td style="text-align:right;">${((totals.totalBounced / totals.totalSent) * 100).toFixed(1)}%</td></tr>
    </table>
    <h2 style="color:#1B3A5C;font-size:14px;border-bottom:2px solid #8CC63F;padding-bottom:4px;margin-top:20px;">Action Items</h2>
    <ol style="font-size:12px;line-height:2;color:#2c3e50;">
      <li><strong style="color:#D94A4A;">${demoDecayAlerts.filter(d => d.decay >= 70).length} decay alerts</strong> — $${demoDecayAlerts.filter(d => d.decay >= 70).reduce((s, d) => s + d.revenue, 0).toLocaleString()} revenue at risk</li>
      <li><strong>${totals.totalBounced} bounced addresses</strong> need cleanup</li>
      <li><strong>${demoChurnScores.filter(c => c.score >= 70).length} high churn risk</strong> members flagged</li>
      <li><strong>${totals.scheduled} campaign</strong> scheduled, ${totals.drafts} draft to review</li>
    </ol>
    <h2 style="color:#1B3A5C;font-size:14px;border-bottom:2px solid #8CC63F;padding-bottom:4px;margin-top:20px;">Top Campaign This Week</h2>
    <p style="font-size:12px;">ALTA ONE Early Bird — 4,994 sent, 45% open rate, $162K revenue generated. Best performing campaign this month.</p>
    <div style="margin-top:20px;padding:12px;background:#f0fdf4;border:1px solid #8CC63F;border-radius:8px;font-size:11px;color:#1B3A5C;">
      <strong>Generated by MEMTrak</strong> — ALTA's internal email intelligence platform
    </div>
  </div>
</div>`;

  return (
    <div className="p-6">
      <h1 className="text-lg font-extrabold text-white mb-6">Daily Briefing Generator</h1>

      <div className="bg-[var(--card)] border border-[var(--card-border)] rounded-xl p-5 mb-6 border-l-4 border-l-[#8CC63F]">
        <p className="text-xs text-white/60">Generate a daily email briefing for the membership team. Print it, copy the HTML to paste into an email, or use the Graph API to send it automatically every morning.</p>
      </div>

      {/* Preview */}
      <div className="bg-white rounded-xl p-0 mb-6 overflow-hidden">
        <div dangerouslySetInnerHTML={{ __html: briefingHtml }} />
      </div>

      <div className="flex gap-3">
        <button onClick={() => printContent('MEMTrak Daily Briefing', briefingHtml)} className="flex items-center gap-2 px-5 py-3 rounded-xl text-sm font-bold text-white bg-[#1B3A5C] hover:bg-[#2a5580]">
          <Printer className="w-4 h-4" /> Print
        </button>
        <button onClick={() => { navigator.clipboard.writeText(briefingHtml); setCopied(true); setTimeout(() => setCopied(false), 2000); }} className="flex items-center gap-2 px-5 py-3 rounded-xl text-sm font-bold text-white bg-[#4A90D9] hover:bg-[#3a7bc0]">
          {copied ? <><CheckCircle className="w-4 h-4" /> Copied!</> : <><Copy className="w-4 h-4" /> Copy HTML</>}
        </button>
        <button className="flex items-center gap-2 px-5 py-3 rounded-xl text-sm font-bold text-white bg-[#8CC63F] hover:bg-[#6fa030]">
          <Mail className="w-4 h-4" /> Email to Team
        </button>
      </div>
    </div>
  );
}
